### ISSUE TITLE
How to combine snapshots (incremental backups) with backup deletion because of TTL?

### ISSUE THREAD

**Issue by sgielen** [openebs/velero-plugin#119]
**Describe the problem/challenge you have**
I created a velero Schedule earlier that would perform a full volume backup every day, with a TTL of 3 days (72 hours).

This has been running for quite a while, but I just found out that all three stored backups are much smaller than the volumes themselves.

I found out that this is because a Backup created from a Snapshot is incremental by default.

This means that my backups are useless: after 72 hours, the initial full backup is deleted by Velero, and the subsequent snapshots are worthless. In my opinion, this (default!) behaviour isn't clearly documented even now that I know about it.

How can I configure my Backups, even those created from a Snapshot, to be non-incremental, or how can I force the plugin to create a new full backup before my the last full backup is deleted because of TTL?

**Describe the solution you'd like**
A method to create a Schedule for which the Backups are full, not incremental. Or even better, a configurable max age of the last full backup after which a new full backup is created instead of an incremental one.

**Anything else you would like to add:**

**Environment:**
- Velero version (use `velero version`): Client v1.5.1, Server v.1.4.0
- Velero features (use `velero client config get features`): <NOT SET>
- Velero-plugin version: ?
- OpenEBS version: v1.11.0
- Kubernetes version (use `kubectl version`): Client 1.19.2, Server 1.18.3+k3s1
- Kubernetes installer & version: k3os
- Cloud provider or hardware configuration: local arm64
- OS (e.g. from `/etc/os-release`): k3os

**Comment by sgielen** [comment]
My workaround is to create this CronJob which automatically creates Backups, just like a Schedule would, but without the backups being incremental...

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: full-volumes-schedule
  namespace: velero
spec:
  schedule: "37 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: velero
          restartPolicy: OnFailure
          containers:
          - name: full-volumes-schedule
            image: ## Velero image here ##
            command:
            - sh
            - -c
            - 'PATH="$PATH:/" velero backup create volumes-full-$(date +%Y%m%d-%H%M%S) --snapshot-volumes=true --ttl 72h --volume-snapshot-locations aws-bucket,default'
```
