### ISSUE TITLE
Automate manual steps to set target-ip

### ISSUE THREAD

**Issue by GBrawl** [openebs/velero-plugin#120]
**Describe the problem/challenge you have**

After restoring a backup you need to update the target-ip's, this can be time-consuming when there's a lot of pvc's and it is easy to make a mistake.

**Describe the solution you'd like**

It would be perfect if these steps could be included in the restore process, but I'm not sure this is possible. Otherwise it would be nice if there was some kind of script which could do this automatically.

**Comment by survivant** [comment]
there is a issue setting with autoSetTargetIP : describe here : https://github.com/openebs/velero-plugin/blob/1129f4a684eadff607cd2b2601c633e0321dd1ed/script/volumesnapshotlocation.yaml

You can automate this process by setting the config parameter autoSetTargetIP to "true" in volumesnapshotlocation
so in the velero.yaml (you give me that information) file I should include that autoSetTargetIP: true ?
```
velero.yaml
    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        bucket: velero
        config:
          region: minio
          s3ForcePathStyle: true
		  publicUrl: 'http://10.1.7.141:9000'
          s3Url: 'http://minio.minio.svc:9000'
      volumeSnapshotLocation:
        name: default
        provider: openebs.io/cstor-blockstore
        config:
          region: minio
          bucket: velero
          provider: aws
          s3Url: 'http://minio.minio.svc:9000'
          s3ForcePathStyle: 'true'
    credentials:
      useSecret: true
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=minio
          aws_secret_access_key=minio123
    snapshotsEnabled: true
    configMaps:
      restic-restore-action-config:
        labels:
          velero.io/plugin-config: ''
          velero.io/restic: RestoreItemAction
        data:
          image: 'gcr.io/heptio-images/velero-restic-restore-helper:v1.1.0'
    deployRestic: true
    initContainers:
      - name: velero-plugin-for-aws
        image: 'velero/velero-plugin-for-aws:v1.1.0'
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-cstor
        image: 'openebs/velero-plugin:2.3.0'
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
```

there are error in the pod

`root@test-pcl114:~/openebs-test/setup-v2# kubectl logs openebs-cstor-csi-node-4kkgv -n openebs cstor-csi-plugin
time="2020-11-20T20:18:01Z" level=info msg="2.3.0 - e2f2a3b7c9ea966831ae55866d7181c434748745"
time="2020-11-20T20:18:01Z" level=info msg="DriverName: cstor.csi.openebs.io Plugin: node EndPoint: unix:///plugin/csi.sock URL: https://openebs.io NodeID: test-pcl114"
time="2020-11-20T20:18:01Z" level=info msg="enabling volume access mode: SINGLE_NODE_WRITER"
time="2020-11-20T20:18:01Z" level=info msg="Listening for connections on address: &net.UnixAddr{Name:\"//plugin/csi.sock\", Net:\"unix\"}"
time="2020-11-20T20:18:22Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":3}}},{\"Type\":{\"Rpc\":{\"type\":2}}}]}"
time="2020-11-20T20:18:22Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":3}}},{\"Type\":{\"Rpc\":{\"type\":2}}}]}"
time="2020-11-20T20:18:22Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":1}}},{\"Type\":{\"Rpc\":{\"type\":3}}},{\"Type\":{\"Rpc\":{\"type\":2}}}]}"
time="2020-11-20T20:18:22Z" level=info msg="GRPC response: {\"usage\":[{\"available\":4915630080,\"total\":5150212096,\"unit\":1,\"used\":217804800},{\"available\":327512,\"total\":327680,\"unit\":2,\"used\":168}]}"
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 32 [running]:
runtime.throw(0x1615edb, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0004a56b8 sp=0xc0004a5688 pc=0x4355a2
runtime.mapassign_faststr(0x1433480, 0xc000376ba0, 0xc000045290, 0x28, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:291 +0x3de fp=0xc0004a5720 sp=0xc0004a56b8 pc=0x414f9e
github.com/openebs/cstor-csi/pkg/utils.WaitForVolumeToBeReady(0xc000045290, 0x28, 0x34, 0x0)
        /go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:190 +0xec fp=0xc0004a5770 sp=0xc0004a5720 pc=0x12d617c
github.com/openebs/cstor-csi/pkg/utils.WaitForVolumeReadyAndReachable(0xc0001d0480, 0x34, 0xc0001d0480)
        /go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:408 +0x42 fp=0xc0004a57e0 sp=0xc0004a5770 pc=0x12d6f42
github.com/openebs/cstor-csi/pkg/driver.(*node).NodeStageVolume(0xc0005123f0, 0x1817720, 0xc000512330, 0xc0007041e0, 0x0, 0x0, 0x0)
        /go/src/github.com/openebs/cstor-csi/pkg/driver/node.go:120 +0x35c fp=0xc0004a5a20 sp=0xc0004a57e0 pc=0x12e2a5c
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1(0x1817720, 0xc000512330, 0x1550240, 0xc0007041e0, 0xc000019ae8, 0x1, 0x1, 0xc000600000)
        /go/pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:5558 +0x86 fp=0xc0004a5a68 sp=0xc0004a5a20 pc=0x86fc16
github.com/openebs/cstor-csi/pkg/utils.logGRPC(0x1817720, 0xc000512330, 0x1550240, 0xc0007041e0, 0xc000406300, 0xc000406320, 0xc000087b78, 0x4fd498, 0x1510ea0, 0xc000512330)
        /go/src/github.com/openebs/cstor-csi/pkg/utils/utils.go:121 +0x1b2 fp=0xc0004a5b18 sp=0xc0004a5a68 pc=0x12d5d02
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler(0x1562060, 0xc0005123f0, 0x1817720, 0xc000512330, 0xc000704180, 0x16afb78, 0x1817720, 0xc000512330, 0xc00051a360, 0x113)
        /go/pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:5560 +0x14b fp=0xc0004a5b88 sp=0xc0004a5b18 pc=0x86da4b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a2600, 0x1829d40, 0xc000546600, 0xc000298200, 0xc00038cbd0, 0x22fe4e0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501 fp=0xc0004a5e38 sp=0xc0004a5b88 pc=0x83fd91
google.golang.org/grpc.(*Server).handleStream(0xc0003a2600, 0x1829d40, 0xc000546600, 0xc000298200, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3d fp=0xc0004a5f68 sp=0xc0004a5e38 pc=0x843e7d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000690000, 0xc0003a2600, 0x1829d40, 0xc000546600, 0xc000298200)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1 fp=0xc0004a5fb8 sp=0xc0004a5f68 pc=0x851601
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0004a5fc0 sp=0xc0004a5fb8 pc=0x464b91
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00050d1a8)
        /usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00050d1a0)
        /usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/openebs/cstor-csi/pkg/utils.(*nonBlockingGRPCServer).Wait(0xc00050d1a0)
        /go/src/github.com/openebs/cstor-csi/pkg/utils/server.go:72 +0x2d
github.com/openebs/cstor-csi/pkg/driver.(*CSIDriver).Run(0xc000372690, 0xc000372690, 0x164dbc8)
        /go/src/github.com/openebs/cstor-csi/pkg/driver/service.go:119 +0xab
main.run(0xc00030b620)
        /go/src/github.com/openebs/cstor-csi/cmd/main.go:92 +0x2f6
main.main.func1(0xc000378a00, 0xc0002c9ac0, 0x0, 0x4)
        /go/src/github.com/openebs/cstor-csi/cmd/main.go:40 +0x2a
github.com/spf13/cobra.(*Command).execute(0xc000378a00, 0xc000138010, 0x4, 0x4, 0xc000378a00, 0xc000138010)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000378a00, 0xc00030b630, 0x1605112, 0x6)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /go/src/github.com/openebs/cstor-csi/cmd/main.go:70 +0x363`
