### ISSUE TITLE
change storage class restore item action

### ISSUE THREAD

**Issue by jr0dd** [openebs/velero-plugin#177]
I just wanted to report that your plugin does not like the change storage class restore item action. The restored datasets never zfs send|receive to the new sc location, but the pvc's and pv's reflect the new sc. This is on the same node. Was just trying to restore a backup from spinning drive zfs pool to a ssd pool. I had to manually run zfs send|receive and edit the zfsvolumes afterwards.

Using `velero/velero-plugin-for-aws:v1.3.0` `openebs/velero-plugin:3.0.0` on velero v1.7.0. 

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-storage-class-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  openebs-zfspv-rust: openebs-zfspv-ssd
```
