### ISSUE TITLE
VolumeSnapshotter plugin doesn't support data movement.

### ISSUE THREAD

**Issue by AmirMohG** [openebs/velero-plugin#196]
I would like to know if datamovement is supported.

**What steps did you take and what happened:**
I installed Velero, configured a volumesnapshotlocation and also the openebs csi, and snapshotclass.
Finally I used the command:
velero backup create backup-volumes --include-namespaces veltest --snapshot-volumes --snapshot-move-data --volume-snapshot-locations=default  --include-resources persistentvolumeclaims,persistentvolumes
but I'm getting the error:
VolumeSnapshotter plugin doesn't support data movement." backup=velero/backup-volumes logSource="pkg/backup/item_backupper.go:584" name=pvc-edc7abc0-d127-487c-b78f-45c4f42d8eec namespace= persistentVolume=pvc-edc7abc0-d127-487c-b78f-45c4f42d8eec resource=persistentvolumes

**What did you expect to happen:**
I expected to get the contents of the pv in the remote object storage.

**Additional Information:**
```
volumesnapshotlocation.yml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero
spec:
  config:
    bucket: velerosnap
    namespace: openebs
    local: "true"
    provider: aws
  provider: openebs.io/cstor-blockstore
```
```
velero installation command
velero install --features=EnableCSI --provider aws --bucket velero --plugins "velero/velero-plugin-for-aws:v1.0.0,velero/velero-plugin-for-csi:v0.4.0,openebs/velero-plugin" --secret-file secret --use-node-agent --backup-location-config region=default,s3ForcePathStyle="true",s3Url=X
```
**Environment:**
- Velero version (use `velero version`):
Client:
        Version: v1.15.0
        Git commit: 1d4f1475975b5107ec35f4d19ff17f7d1fcb3edf
Server:
        Version: v1.15.0

- Velero-plugin version:
openebs/velero-plugin:1.11.0
also tried with openebs/velero-plugin
- OpenEBS version:
image: openebs/node-disk-manager:ci
          image: openebs/node-disk-operator:ci
          image: openebs/node-disk-exporter:ci
          image: openebs/node-disk-exporter:ci
          image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.2.2
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          image: registry.k8s.io/sig-storage/csi-attacher:v4.3.0
          image: openebs/cstor-csi-driver:ci
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
          image: openebs/cstor-csi-driver:ci
          image: openebs/cspc-operator:ci
          image: openebs/cvc-operator:ci
          image: openebs/cstor-webhook:ci
- Kubernetes version (use `kubectl version`):
Server Version: v1.28.2
- Cloud provider or hardware configuration:
On-prem
- OS (e.g. from `/etc/os-release`):
Ubuntu 22.04.3 LTS
