### ISSUE TITLE
Prefix in volumesnapshotlocation is working as a file

### ISSUE THREAD

**Issue by amarshaw** [openebs/velero-plugin#22]
Prefix in volumesnapshotlocation is working as a file, its should work as a director.

Because of this our snapshot volumes are store in different location and backups are partially failed.

**Comment by mynktl** [comment]
Hi @amarshaw, we have added a new parameter `backupPathPrefix` in `VolumeSnapshotLocation` for backup path. So, sample `VolumeSnapshotLocation` is as below : 
```
spec:
  provider: openebs.io/cstor-blockstore
  config:
    bucket: <YOUR_BUCKET>
    prefix: <PREFIX_FOR_BACKUP_NAME>
    backupPathPrefix: <PREFIX_FOR_BACKUP_PATH>
    provider: <GCP_OR_AWS>
    region: <AWS_REGION>
```
So, if you have..
```
prefix:"cstor"
backupPathPrefix:"newbackup"
```
and backup_name is `test1` then backup files of CStor Volumes will be stored at `bucket_name/newbackup/backups/test1/cstor-backup_file-test1`
